### ISSUE TITLE
Støtte for sending av flere dokumenter - ref versjon 1.2.4 av grensesnitt dokumentasjonen

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-java-eksempel-webclient#10]
støtte for: https://github.com/difi/begrep-SikkerDigitalPost/releases/tag/1.2.4
ta i bruk klientbiblioteket i oppdatert versjon når det er levert, ref: https://github.com/difi/sikker-digital-post-klient-java/issues/56

intern ref: PBLEID-12763

**Comment by oyri** [comment]
Dette er utført inkl. oppgradering til java 8. Implementasjonen ligg i master branchen og http://test-avsender-sdp.difi.local:8080/ er oppdatert med siste versjon.
