### ISSUE TITLE
Felaktiga brukare i digipost_yt_testbrukere.csv

### ISSUE THREAD

**Issue by kagkarlsson** [difi/sikker-digital-post-java-eksempel-webclient#11]
digipost_yt_testbrukere.csv inneholder ett par linjer på fel format:

2202921;368;testbruker.f.criasg#7C0Q
15089015585;6581;testbruker.f.tnudaz#117K

**Comment by kagkarlsson** [comment]
@aberner

**Comment by oyri** [comment]
Brukarar retta i csv-fil.
