### ISSUE TITLE
Støtte for forsendelser med tittel på opp til 255 tegn

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-java-eksempel-webclient#15]
ref: https://github.com/difi/begrep-SikkerDigitalPost/issues/191
ref: https://github.com/difi/sikker-digital-post-klient-java/issues/70

Det er behov for at testklienten http://avsender-sdp.difi.no/client/ er oppdatert med endringen beskrevet over før funksjonell testing starter i mai.

**Comment by rocketfarmsteinar** [comment]
Hei Arne.

Den er grei. Tenker vi tek dette så kjapt det let seg gjere, men må komme tilbake til akkurat når.

**Comment by aknutsen** [comment]
Ny versjon ble lastet opp før sommeren, så denne skal være i orden.
