### ISSUE TITLE
Oppgradere integrasjonen mot kontaktregisteret

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-java-eksempel-webclient#3]
Gå over til versjon 4. av oppslagstjenesten.

**Comment by oyri** [comment]
Me bør gå over til å ta i bruk versjon 5 av kontaktregisteret i staden for versjon 4.

**Comment by iko3** [comment]
This client is not compatible with v5 of Oppslagstjenesten, right?

Getting "Tjenesten er for tiden ikke tilgjengelig" when changing the endpoint to the latest version (https://kontaktinfo-ws-ver1.difi.no/kontaktinfo-external/ws-v5)

**Comment by oyri** [comment]
That is correct. This issue is about upgrading new version of Oppslagstjenesten and it is not started on.

**Comment by iko3** [comment]
Thanks for the info.

A little out of topic question: I'm constantly getting "500: Tjenesten er for tiden ikke tilgjengelig" when connecting against v5 test environment, does that indicate that the endpoint is not functioning properly or that there is an error in the request? If 2nd option, how can I debug it and get more informative description? Previous version was throwing more detailed error messages :)

**Comment by joergenb** [comment]
Are you using VER1 or VER2 test environment ?  Do you have the timestamps for your attempts? It seems to be working fine according to recent log messages.

We've seen 500 errors when clients use the wrong SOAP version. v5 is using 1.2, whereas v4 used 1.1.
Normally errors in the request should lead to us returning HTTP 400 if the error is "low-level", if the error is somewhat more "high-level" you should still get the customized Difi error messages, they have not been abandoned.

**Comment by iko3** [comment]
@joergenb  It is ver1 and SOAP version is 1.2

I attached my request here, maybe you will be able to say what is missing.
https://gist.github.com/iko3/ec0f8de3b9ec4db3ab9d

**Comment by joergenb** [comment]
I struggle to identify an error in that request :(. But I do find error messages in the log relating to wrong HTTP headers which might be the cause?

incorrect content-type for SOAP version. Got: text/xml; charset=UTF-8 Expected: application/soap+xml

**Comment by iko3** [comment]
I managed to fix it, there was a problem with an interceptor. Thanks for the help :)

**Comment by aberner** [comment]
@oyri denne er vel fikset nå og kan lukkes?

**Comment by oyri** [comment]
The client is now upgraded to v5 of Oppslagstjensten.
