### ISSUE TITLE
Endring av rapporten produsert

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-java-eksempel-webclient#7]
- Det er ønskelig å få et endret format på rapporten for å forenkle prosesseringen av den etter en ytelsestest
- Det er avtalt et annet format enn det test-avsenderne bruker med postkassleverandørene, dersom formatet endres kan vi enklere gjenbruke script for å prosessere loggene og vurdere resultatene ved en ytelsestest.
- Formatet som ønskes er: CSV, semikolon separert
- Tidsformat i: ISO8601_timestamp (date and time), eks: "2015-09-24 14:58:41"
- Tidene: … RequestSentDate … ResponseReceivedDate endres slik at rapporten kun rapporterer millisekundene mellom de to tidsstemplene.

**Comment by aknutsen** [comment]
Hei, jeg er på denne saken nå, men har noen spørsmål: 

1. ISO8601 har gjerne format "2015-09-24T14:58:41", men i følge eksempelet skal formatet ikke inneholde T, men ha mellomrom mellom dato og klokkeslett. Stemmer det?

2. "Tidene: … RequestSentDate … ResponseReceivedDate endres slik at rapporten kun rapporterer millisekundene mellom de to tidsstemplene."
Kan denne utdypes litt mer? Skal en eller flere verdier bort fra rapporten? Skal ResponseReceivedDate byttes ut med differansen mellom de to verdiene?

- Anders

**Comment by aberner** [comment]
@aknutsen T'n kan være med. det har vært litt frem og tilbake på det formatet. så hold deg til standarden. der er bra.

requestSentDate og ResponseReceivedDate erstattes med requestSendtime som skal være antall millisekunder mellom de to tidsstemplene. (dette er slik andre rapporter fra leverandørene leveres og det vil forenkle rapport genereringen etterpå.)

Det samme for: receiptRequestSentDate og receiptResponseReceivedDate erstattes med erstattes med receiptResponseTime som skal være antall millisekunder mellom de to tidsstemplene.

**Comment by aberner** [comment]
@aknutsen hei, jeg tror ikke installasjonen her er oppdatert: http://avsender-sdp.difi.no/ stemmer det? kan dere få deployet ut en ny versjon dit, slik at jeg kan få testet ut det nye rapportformatet?

**Comment by aknutsen** [comment]
@aberner Det stemmer nok. Jeg skal se på det.

**Comment by aknutsen** [comment]
@aberner Nå skal ny versjon være lastet opp.
