### ISSUE TITLE
Støtte for sending av store dokumenter/forsendelser

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-java-eksempel-webclient#9]
I dag er det en begrensing i testavsenderen installert her: http://avsender-sdp.difi.no/ver2/
begrensningen er testet komplett men det ser ut til at det ikke fungerer å sende mer enn 4 til 8 mb i en forsendelse.

Det er behov for å kunne sende større forsendelser. Behovet er at man skal kunne teste å sende opp til 100 MB.
Dersom det er vanskelig å realiseres er det i første omgang behov for å kunne sende opp til 25 MB.

Merk:
- en forsendelse er summen av størrelsen av både hoveddokument og vedlegg. 
  Enten et stort hoveddokument eller vedlegg, eller at alle totalt har en bestemt størrelse.

**Comment by aberner** [comment]
Feilmeldingen som gis fra Testavsender er: "413 Request Entity Too Large" når det sendes mer enn ca. 9 - 10 MB dokumenter.
Antagelsen er at det er nginx konfigurasjonen som må endres på følgende parameter:
client_max_body_size
Ønske er at denne settes til 30 MB.
mulig det er andre begrensninger også i test-avsenderen.

**Comment by oyri** [comment]
For http://test-avsender-sdp.difi.local:8080/ er desse endringane utført for å støtte store dokument:
- nginx konfigurasjon endra til å tillate opp til 30MB dokument
- mysql database endra til å håndtere store dokument ved lagring
